[workspace]
resolver = "2"
members = [
  "integration",
  "components/atc-algorithm",
  "components/atc-vm",
  "components/a-townchain/modules/atc-blockchain/kernel",
  "components/atc-marketplace/modules/atc-dex",
  "components/atc-mining",
  "components/atc-node",
  "components/atc-sdk",
  "components/atc-indexer",
  "components/atc-wallet",
  "components/aurora-ai/modules/atc-aurora-core",
  "components/aurora-ai/modules/atc-aurora-memory",
  "components/aurora-ai/modules/atc-aurora-runtime",
  "components/aurora-ai/modules/atc-aurora-policy",
  "components/aurora-ai/modules/atc-aurora-tools",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
