[workspace]
resolver = "2"
members = [
  "integration",
  "components/atc-node",
  "components/atc-sdk",
  "components/atc-l2",
]

[workspace.exclude]
members = [
  "components/atclang/crates/atc-core",
  "components/atc-shivacore/modules/atc-security",
  "components/atc-shivacore/sdk",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
