[package]
name = "atc-blockchain"
version = "1.0.0"
edition = "2021"
license = "Apache-2.0"
[lib]
name = "atc_blockchain"
path = "src/blockchain.rs"
[dependencies]
sha2 = "0.10"
ed25519-dalek = { version = "2", features = ["rand_core"] }
atc-algorithm = { path = "../../../../atc-algorithm" }
atc-vm = { path = "../../../../atc-vm" }
hex = "0.4"
serde = { version = "1", features = ["derive"] }
