//! Transactions, mempool and deterministic state transition.
use std::{collections::BTreeMap,sync::Mutex};use crate::security::simple_hash;
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum TxType{Transfer=0,Stake=1,Unstake=2,Contract=3}impl TxType{pub fn base_gas(self)->u64{match self{Self::Transfer=>1000,Self::Stake=>1200,Self::Unstake=>1200,Self::Contract=>5000}}}
#[derive(Clone,Debug,PartialEq,Eq)]pub struct Transaction{pub id:[u8;32],pub tx_type:TxType,pub sender_did:String,pub recipient_did:Option<String>,pub amount:u64,pub gas_price:u64,pub gas_limit:u64,pub nonce:u64,pub timestamp:u64,pub payload:Vec<u8>,pub signature:[u8;64],pub poh_hash:[u8;32]}
impl Transaction{pub fn new(t:TxType,s:String,r:Option<String>,a:u64,gp:u64,gl:u64,n:u64,ts:u64,p:Vec<u8>,sig:[u8;64],poh:[u8;32])->Self{let mut b=Vec::new();b.push(t as u8);b.extend_from_slice(s.as_bytes());if let Some(x)=&r{b.extend_from_slice(x.as_bytes())}b.extend_from_slice(&a.to_be_bytes());b.extend_from_slice(&gp.to_be_bytes());b.extend_from_slice(&gl.to_be_bytes());b.extend_from_slice(&n.to_be_bytes());b.extend_from_slice(&ts.to_be_bytes());b.extend_from_slice(&poh);b.extend_from_slice(&p);Self{id:simple_hash(&b),tx_type:t,sender_did:s,recipient_did:r,amount:a,gas_price:gp,gas_limit:gl,nonce:n,timestamp:ts,payload:p,signature:sig,poh_hash:poh}}pub fn gas_cost(&self)->u64{self.tx_type.base_gas()+self.payload.len()as u64*10}pub fn max_fee(&self)->u64{self.gas_limit.saturating_mul(self.gas_price)}}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum TxStatus{Pending,Validated,InBlock,Rejected,Expired}
#[derive(Clone,Debug)]pub struct PoolEntry{pub tx:Transaction,pub status:TxStatus,pub added_at:u64,pub priority:u64}
#[derive(Debug,Clone,PartialEq,Eq)]pub enum MempoolError{PoolFull,DuplicateTx,TxNotFound,GasLimitTooLow,GasPriceTooLow,NoRecipient,InvalidNonce{expected:u64,got:u64},InsufficientBalance,InsufficientStake,Expired}
pub struct MemoryPool{entries:Mutex<BTreeMap<[u8;32],PoolEntry>>,max_size:usize,max_age:u64}impl MemoryPool{pub fn new(m:usize,a:u64)->Self{Self{entries:Mutex::new(BTreeMap::new()),max_size:m,max_age:a}}pub fn add(&self,tx:Transaction,now:u64)->Result<(),MempoolError>{let mut e=self.entries.lock().unwrap();if e.contains_key(&tx.id){return Err(MempoolError::DuplicateTx)}if e.len()>=self.max_size{return Err(MempoolError::PoolFull)}let id=tx.id;e.insert(id,PoolEntry{priority:tx.gas_price.saturating_mul(tx.gas_limit),tx,status:TxStatus::Pending,added_at:now});Ok(())}pub fn validate_tx(&self,id:&[u8;32],now:u64)->Result<(),MempoolError>{let mut e=self.entries.lock().unwrap();let x=e.get_mut(id).ok_or(MempoolError::TxNotFound)?;if now.saturating_sub(x.added_at)>self.max_age{x.status=TxStatus::Expired;return Err(MempoolError::Expired)}if x.tx.gas_limit<x.tx.gas_cost(){x.status=TxStatus::Rejected;return Err(MempoolError::GasLimitTooLow)}if x.tx.gas_price==0{x.status=TxStatus::Rejected;return Err(MempoolError::GasPriceTooLow)}if x.tx.tx_type==TxType::Transfer&&x.tx.amount>0&&x.tx.recipient_did.is_none(){x.status=TxStatus::Rejected;return Err(MempoolError::NoRecipient)}x.status=TxStatus::Validated;Ok(())}pub fn get_pending_batch(&self,n:usize)->Vec<Transaction>{let e=self.entries.lock().unwrap();let mut v:Vec<_>=e.values().filter(|x|x.status==TxStatus::Validated).cloned().collect();v.sort_by(|a,b|b.priority.cmp(&a.priority).then(a.tx.id.cmp(&b.tx.id)));v.into_iter().take(n).map(|x|x.tx).collect()}pub fn mark_in_block(&self,id:&[u8;32]){if let Some(x)=self.entries.lock().unwrap().get_mut(id){x.status=TxStatus::InBlock}}}
#[derive(Clone,Debug,PartialEq,Eq)]pub struct Account{pub balance:u64,pub staked:u64,pub nonce:u64}pub struct StateDb{accounts:Mutex<BTreeMap<String,Account>>}impl StateDb{pub fn new()->Self{Self{accounts:Mutex::new(BTreeMap::new())}}pub fn deposit(&self,id:&str,n:u64){let mut a=self.accounts.lock().unwrap();let x=a.entry(id.into()).or_insert(Account{balance:0,staked:0,nonce:0});x.balance=x.balance.saturating_add(n)}pub fn balance(&self,id:&str)->u64{self.accounts.lock().unwrap().get(id).map(|x|x.balance).unwrap_or(0)}pub fn nonce(&self,id:&str)->u64{self.accounts.lock().unwrap().get(id).map(|x|x.nonce).unwrap_or(0)}pub fn root(&self)->[u8;32]{let a=self.accounts.lock().unwrap();let mut b=Vec::new();for(k,v)in a.iter(){b.extend_from_slice(k.as_bytes());b.extend_from_slice(&v.balance.to_be_bytes());b.extend_from_slice(&v.staked.to_be_bytes());b.extend_from_slice(&v.nonce.to_be_bytes())}simple_hash(&b)}pub fn apply(&self,tx:&Transaction)->Result<(),MempoolError>{let mut a=self.accounts.lock().unwrap();let s=a.get(&tx.sender_did).cloned().unwrap_or(Account{balance:0,staked:0,nonce:0});if s.nonce!=tx.nonce{return Err(MempoolError::InvalidNonce{expected:s.nonce,got:tx.nonce})}if s.balance<tx.amount.saturating_add(tx.max_fee()){return Err(MempoolError::InsufficientBalance)}let mut ns=s;ns.balance-=tx.amount+tx.max_fee();ns.nonce+=1;a.insert(tx.sender_did.clone(),ns);if tx.tx_type==TxType::Transfer{let r=tx.recipient_did.as_ref().ok_or(MempoolError::NoRecipient)?;let x=a.entry(r.clone()).or_insert(Account{balance:0,staked:0,nonce:0});x.balance=x.balance.saturating_add(tx.amount)}Ok(())}}
