[package]
name = "atc-ecosystem-integration"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
atc-node = { path = "../components/atc-node" }
atc-sdk = { path = "../components/atc-sdk" }
atc-blockchain = { path = "../components/a-townchain/modules/atc-blockchain/kernel" }
ed25519-dalek = { version = "2", features = ["rand_core"] }
